blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    # path('' , views.home, name='home'),
    path('blog/' , views.BlogListView.as_view(), name='blog_list'),
    # path('blog/' , views.bloglist, name='blog_list'),
    path('<slug:blog_slug>' , views.blogdetail, name='blog_detail')
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('', include('blog.urls', namespace='blogs')),
    path('tinymce/', include('tinymce.urls')),
    path('', include("django.contrib.auth.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils.text import slugify


# Create your models here.


class Blog(models.Model):
    blog_title = models.CharField(max_length=200)
    blog_content = models.TextField()
    category = models.ForeignKey('BlogCategory', on_delete=models.SET_NULL, null=True)
    blog_published = models.DateTimeField('date published', default=datetime.now)
    slug = models.SlugField(blank=True,null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.blog_title:
            self.slug = slugify(self.blog_title)
        super(Blog,self).save(*args, **kwargs)


    def __str__(self):
        return self.blog_title


class BlogCategory(models.Model):
    blog_category = models.CharField(max_length=200)
    blog_summary = models.CharField(max_length=200)

    class Meta:
        # Gives the proper plural name for admin
        verbose_name_plural = "Categories"


    def __str__(self):
        return self.blog_category


class ContactForm(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

class Comment(models.Model):
    blog = models.ForeignKey('Blog', on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, null=True, related_name='replies')
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}.{}'.format(self.blog.blog_title, str(self.user.username))

register/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django.forms import ModelForm
from django import forms
from .models import ContactForm,Comment

class Contact(forms.ModelForm):
    name = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField(widget=forms.Textarea)
    class Meta:
        model = ContactForm
        fields = '__all__'

class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Text goes here!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

blog/views.py
from django.shortcuts import render, redirect

from django.views.generic import View, TemplateView, ListView,  DetailView, UpdateView
from .models import Blog,BlogCategory,Comment
from .forms import Contact,CommentForm

# Create your views here.
class Home(TemplateView):
    template_name = 'base.html'

# def home(request):
#     template = 'base.html'
#     return render(request, template)

class BlogListView(ListView):
    form = Contact()
    model = Blog
    template_name = 'Blog/blog_list.html'
    context_object_name = 'blog_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = Contact(request.POST)
        if form.is_valid():
            form.save(commit=True)
        else:
            print('ERROR FORM INVALID')
        return redirect("/")




# def bloglist(request):
#     bloglist = Blog.objects.all()
#     template = 'Blog/blog_list.html'
#
#     form = Contact()
#     if request.method == "POST":
#         form = Contact(request.POST)
#         if form.is_valid():
#             form.save(commit=True)
#             return home(request)
#         else:
#             print('ERROR FORM INVALID')
#
#     context = {'blog_list':bloglist, 'form':form}
#     return render(request, template, context)

def blogdetail(request, blog_slug):
    print(blog_slug)
    blogdetail = Blog.objects.get(slug=blog_slug)
    blogcategory = Blog.objects.filter(category=blogdetail.category).order_by('blog_published')
    blogdetail_idx = list(blogcategory).index(blogdetail)
    comments = Comment.objects.filter(blog=blogdetail, reply=None).order_by('-id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(blog=blogdetail, user=request.user, content=content, reply=comment_qs)
            comment.save()
    else:
        comment_form = CommentForm()

    template = 'Blog/blog_detail.html'
    context = {'blog_detail':blogdetail, 'sidebar':blogcategory, 'blog_idx':blogdetail_idx, 'comments':comments, 'comment_form':comment_form}
    return render(request, template, context)

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("/login/")
    else:
        form = RegisterForm()
    return render(request, "register/register.html", {"form":form})

blog/templates/Blog/blog_detail.html
{% extends 'base.html' %}

{% block home %}
{% endblock home %}

{% block resume %}
{% endblock resume %}

{% block about %}
{% endblock about %}

{% block social %}
{% endblock social %}

{% block contact %}
{% endblock contact %}

{% block body %}

<div class="container">
<div class="row">

    <div class="col s12, m8, l8">
      <br>
        <h3>{{blog_detail.blog_title}}</h3>
        <p style="font-size:70%">Published On: {{blog_detail.blog_published}}</p>
        {{blog_detail.blog_content|safe}}
    </div>

    <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for blog in sidebar %}
                    {% if forloop.counter0 == blog_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{blog.blog_title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{blog.blog_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/{{blog.slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
</div>

<br><br>
<hr>



<div class="main-comment-section">
  <div class="container-fluid mt-2">
    <div class="form-group row">
      <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated %}
          <input type="submit" value="Comment" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Comment" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>

  </div>

  {{ comments.count }} Comment{{ comments|pluralize }}

  {% for comment in comments %}
  <blockquote class="blockquote">
    <p class="mb-0"><small>{{comment.content}}</small></p>
    <footer class="blockquote-footer">by <cite title="Source Title">{{comment.user|capfirst}}</cite>
      <br>
      <br>
      <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
    </footer>
  </blockquote>

  <div class="replied-comments container mt-2" style="display:none;">
    {% for reply in comment.replies.all %}
        <blockquote class="blockquote">
          <p class="mb-0"><small>{{reply.content}}</small></p>
          <footer class="blockquote-footer">by <cite title="Source Title">{{reply.user|capfirst}}</cite></footer>
        </blockquote>
    {% endfor %}
    <div class="form-group row">
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{comment.id}}">
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated %}
          <input type="submit" value="Submit" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>
  </div>
  {% endfor %}

</div>

</div>

{% endblock body %}

blog/templates/Blog/blog_list.html
{% extends 'base.html' %}

{% block home %}
{% endblock home %}

{% block resume %}
{% endblock resume %}

{% block about %}
{% endblock about %}

{% block social %}
{% endblock social %}

{% block contact %}
{% endblock contact %}

{% block body %}

<div class="container">
<div class="row">
  <br>
  <br>
{% for blog in blog_list %}
<div class="col s12 m6 l4">
    <a href="{% url 'blogs:blog_detail' blog.slug %}", style="color:#000">
        <div class="card hoverable grey">
            <div class="card-content">
                <div class="card-title">{{blog.category}}</div>
                <p style="font-size:70%">Published {{blog.blog_published}}</p>
                <p>{{blog.category.blog_summary}}</p>
            </div>
        </div>
    </a>
</div>

{% endfor %}
</div>
</div>

<section id="contact" class="tm-contact">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="title">Drop <strong>me a line</strong></h2>
      </div>
      <div class="col-md-1 col-sm-1"></div>
      <div class="col-md-10 col-sm-10">
        <div class="ui inverted segment">
        <form method="POST" class="ui inverted form">
          {{form.as_p}}
          {% csrf_token %}

      </div>
          <button class="ui button black" type="submit" value="Submit">Submit</button>
        </form>
      </div>
      <div class="col-md-1 col-sm-1"></div>
      <div class="col-md-12 col-sm-12">
      </div>
    </div>
  </div>
</section>
{% endblock body %}

register/templates/register/register.html
{% extends "base.html" %}

{% block home %}
{% endblock home %}

{% block resume %}
{% endblock resume %}

{% block about %}
{% endblock about %}

{% block social %}
{% endblock social %}

{% block contact %}
{% endblock contact %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="container">
  <h2>Create an Account</h2>
  <form method="POST" class="form-group">
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <br>
    <button type="submit" class="btn btn-success">Register</button>
  </form>
  </div>
{% endblock body %}

templates/base.html
<head>

    {% load static %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
      $(".reply-btn").click(function(){
        $(this).parent().parent().next(".replied-comments").fadeToggle();
      });
    });
  </script>

    <!-- semantic UI -->
  <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>



    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
  	<link rel="stylesheet" href="{% static "css/templatemo-style.css" %}">
  	<link href='//fonts.googleapis.com/css?family=Raleway:400,300,600,700' rel='stylesheet' type='text/css'>


    <!-- Prism CSS -->
    <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static "css/materialize.css" %}">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>




</head>


<body>
  <nav class="black">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a href="{% url 'blogs:blog_list' %}">Blog</a></li>
        <li><a href="/register/">Register</a></li>
        <li><a href="/login/">Login</a></li>
        <li><a href="/logout/">Logout</a></li>
      </ul>
    </div>
  </nav>

  <!-- START HOME -->
  {% block home %}
	<section id="home" class="templatemo-home">
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-sm-1"></div>
				<div class="col-md-8 col-sm-10">
					<h1 class="tm-home-title"><strong>CodeyPY</strong></h1>
					<h2 class="tm-home-subtitle">Web Developer</h2>
					<p>I am a professional <strong>Web Developer</strong> and <strong>Front-End Developer</strong> creating modern and responsive designs for <strong>Web</strong> and <strong>Mobile</strong>. Let us work together. Thank you.</p>

				</div>
				<div class="col-md-2 col-sm-1"></div>
			</div>
		</div>
	</section>
  {% endblock home %}
  <!-- END HOME -->

  <!-- START RESUME -->
{% block resume %}
	<section id="resume" class="tm-padding-top-bottom-100">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-sm-6">
					<h2 class="title">My <strong>Profile</strong></h2>
					<p><span class="tm-info-label">Name</span> Jun Kalita</p>
					<p><span class="tm-info-label">Birthday</span> March 16, 1996</p>
					<p><span class="tm-info-label">Address</span> Assam, India</p>
					<p><span class="tm-info-label">Phone</span> +91 8473803520 | 009 080 0760</p>
					<p><span class="tm-info-label">Email</span> junkalita18@gmail.com</p>
					<p><span class="tm-info-label">Website</span> <a href="#" class="tm-red-text">www.company.com</a></p>
				</div>
				<div class="col-md-6 col-sm-6">
					<h2 class="title"><strong>Some</strong> Skills</h2>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet. Dolore magna aliquam erat volutpat.</p>
					<h4 class="tm-progress-label">Django <small class="progress-percent-small">100%</small></h4>
					<div class="progress tm-progress">
						<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;"></div>
					</div>
					<h4 class="tm-progress-label">Python <small class="progress-percent-small">90%</small></h4>
					<div class="progress tm-progress">
						<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
					</div>
					<h4 class="tm-progress-label">HTML-5 <small class="progress-percent-small">80%</small></h4>
					<div class="progress tm-progress">
						<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"></div>
					</div>
				</div>
			</div>
		</div>
	</section>
  {% endblock resume %}
	<!-- END RESUME -->

  <!-- START ABOUT -->
  {% block about %}
	<section id="about" class="tm-about">
		<div class="container">
			<div class="row">
				<div class="col-md-offset-6 col-md-6 col-sm-offset-6 col-sm-7">
					<div class="title">
						<h2>This is <strong>me</strong></h2>
						<h1 class="tm-red-text">Creative <strong>Director</strong></h1>
					</div>
					<p>This is free Bootstrap v3.3.4 mobile friendly layout from <a rel="nofollow" href="https://templatemo.com">templatemo</a>. Feel free to use it for your website. Credit goes to <a rel="nofollow" href="https://pixabay.com">Pixabay</a> for photos used in this template. Dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.</p>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet. Dolore magna aliquam erat volutpat.</p>
				</div>
			</div>
		</div>
	</section>
  {% endblock about %}
	<!-- END ABOUT -->

	<!-- START SOCIAL -->
  {% block social %}
	<section id="social" class="tm-social">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-4 wow rotateInUpLeft" data-wow-delay="0.3s">
					<div class="media facebook">
						<a href="#">
							<div class="media-object pull-left">
								<i class="fa fa-facebook"></i>
							</div>
							<div class="media-body">
								<h4 class="media-heading tm-social-title">Follow me on</h4>
								<h3>Social Facebook</h3>
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 wow rotateInUpLeft" data-wow-delay="0.6s">
					<div class="media twitter">
						<a href="#">
							<div class="media-object pull-left">
								<i class="fa fa-twitter"></i>
							</div>
							<div class="media-body">
								<h4 class="media-heading tm-social-title">Tweet me on</h4>
								<h3>Social Twitter</h3>
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 wow rotateInUpLeft" data-wow-delay="0.9s">
					<div class="media pinterest">
						<a href="#">
							<div class="media-object pull-left">
								<i class="fa fa-pinterest"></i>
							</div>
							<div class="media-body">
								<h4 class="media-heading tm-social-title">Pin me on</h4>
								<h3>Social Pinterest</h3>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>
  {% endblock social %}
	<!-- END SOCIAL -->

	<!-- START CONTACT -->
  {% block contact %}

  {% endblock contact %}
	<!-- END CONTACT -->


  {% block body %}

  {% endblock body %}


</body>


<!-- Prism JS -->
<script src="{% static "tinymce/js/prism.js" %}"></script>
<script>M.AutoInit();</script>


<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/smoothscroll.js" %}"></script>
<script src="{% static "js/jquery.nav.js" %}"></script>
<script src="{% static "js/isotope.js" %}></script>
<script src="{% static "js/imagesloaded.min.js" %}></script>
<script src="{% static "js/custom.js" %}></script>